#!/usr/bin/env python3
"""
YOLO Training Pipeline for Zedsu Phase 11.
Automates: dataset split -> data.yaml -> train -> export ONNX -> install.
D-11b: CLI only, no in-app training.
D-11b-03: Auto-detect CUDA/CPU.
D-11c-01: Auto-backup on successful training.
"""
import argparse
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime

# Target classes from YOLODetector.CLASS_NAMES
CLASS_NAMES = {
    0: "ultimate_bar",
    1: "solo_button",
    2: "br_mode_button",
    3: "return_to_lobby",
    4: "open_button",
    5: "continue_button",
    6: "combat_ready",
    7: "change_button",
    8: "enemy_player",
    9: "afk_cluster",
}


def detect_hardware() -> tuple:
    """
    Detect CUDA GPU availability.
    Returns: (device_string, hardware_label, is_cuda)
    """
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=name", "--format=csv,noheader"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0 and result.stdout.strip():
            gpu_name = result.stdout.strip().split('\n')[0]
            return ("cuda", f"GPU ({gpu_name})", True)
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        pass

    return ("cpu", "CPU", False)


def ensure_dataset_structure(dataset_root: str, val_split: float = 0.2) -> bool:
    """
    Ensure dataset has train/val split structure.
    If images are in dataset_root/{class}/, split them into train/val.
    If train/val already exists, skip.
    """
    train_images = os.path.join(dataset_root, "train", "images")
    val_images = os.path.join(dataset_root, "val", "images")

    if os.path.isdir(train_images) and os.path.isdir(val_images):
        print("[OK] Dataset already split (train/val found)")
        return True

    # Find all images grouped by class
    all_images_by_class = {}
    for class_id, class_name in CLASS_NAMES.items():
        class_dir = os.path.join(dataset_root, class_name)
        if os.path.isdir(class_dir):
            images = [
                os.path.join(class_dir, f)
                for f in os.listdir(class_dir)
                if f.lower().endswith(('.png', '.jpg', '.jpeg'))
            ]
            if images:
                all_images_by_class[class_name] = images

    if not all_images_by_class:
        print("[ERROR] No labeled images found in dataset_yolo/{class}/")
        return False

    print(f"[INFO] Found {sum(len(v) for v in all_images_by_class.values())} images across {len(all_images_by_class)} classes")

    # Create train/val directories
    for split in ("train", "val"):
        for class_name in CLASS_NAMES.values():
            os.makedirs(os.path.join(dataset_root, split, "images", class_name), exist_ok=True)
            os.makedirs(os.path.join(dataset_root, split, "labels", class_name), exist_ok=True)

    # Split and copy images for each class
    import random
    for class_name, images in all_images_by_class.items():
        random.shuffle(images)
        split_idx = int(len(images) * (1 - val_split))
        train_imgs = images[:split_idx]
        val_imgs = images[split_idx:]

        for img_path in train_imgs:
            _copy_image_and_label(img_path, dataset_root, "train", class_name)
        for img_path in val_imgs:
            _copy_image_and_label(img_path, dataset_root, "val", class_name)

        print(f"  {class_name}: {len(train_imgs)} train, {len(val_imgs)} val")

    return True


def _copy_image_and_label(src_img_path: str, dataset_root: str, split: str, class_name: str):
    """Copy image and its YOLO label to the split directory."""
    filename = os.path.basename(src_img_path)
    dst_img = os.path.join(dataset_root, split, "images", class_name, filename)
    shutil.copy(src_img_path, dst_img)

    label_path = os.path.splitext(src_img_path)[0] + ".txt"
    if os.path.exists(label_path):
        dst_label = os.path.join(dataset_root, split, "labels", class_name, os.path.basename(label_path))
        shutil.copy(label_path, dst_label)


def create_data_yaml(dataset_root: str) -> str:
    """Generate data.yaml for training. Returns path to the yaml file."""
    yaml_path = os.path.join(dataset_root, "data.yaml")

    names_list = [CLASS_NAMES[i] for i in sorted(CLASS_NAMES.keys())]
    names_yaml = "\n".join(f"  {i}: {name}" for i, name in enumerate(names_list))

    content = f"""# Auto-generated by train_yolo.py (Phase 11)
# Do not edit manually
path: {os.path.abspath(dataset_root)}
train: train/images
val: val/images

names:
{names_yaml}

nc: {len(CLASS_NAMES)}
"""

    with open(yaml_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[INFO] Created {yaml_path}")
    return yaml_path


def backup_current_model(assets_dir: str) -> str:
    """
    Backup current yolo_gpo.onnx to timestamped backup.
    D-11c-01: Auto-backup on train success.
    Returns: path to backup file or empty string if no model to backup.
    """
    model_path = os.path.join(assets_dir, "models", "yolo_gpo.onnx")
    if not os.path.exists(model_path):
        return ""

    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    backup_path = os.path.join(assets_dir, "models", f"yolo_gpo_backup_{timestamp}.onnx")

    shutil.copy2(model_path, backup_path)
    print(f"[BACKUP] {model_path} -> {backup_path}")
    return backup_path


def run_training(data_yaml: str, model_size: str, epochs: int, device: str) -> str:
    """
    Run YOLO training via ultralytics CLI.
    Returns: path to best weights.
    """
    model_pt = f"{model_size}.pt"
    print(f"\n[TRAIN] Starting YOLO training...")
    print(f"  Model: {model_pt}")
    print(f"  Epochs: {epochs}")
    print(f"  Device: {device}")
    print(f"  Data: {data_yaml}")

    cmd = [
        sys.executable, "-m", "ultralytics", "detect", "train",
        f"data={data_yaml}",
        f"model={model_pt}",
        f"epochs={epochs}",
        "imgsz=640",
        f"device={device}",
        "patience=20",
        "verbose=True",
    ]

    print(f"\n[CMD] {' '.join(cmd)}\n")

    start_time = time.time()
    result = subprocess.run(cmd, cwd=os.getcwd())
    elapsed = time.time() - start_time

    if result.returncode != 0:
        print(f"[ERROR] Training failed with exit code {result.returncode}")
        return ""

    print(f"[OK] Training completed in {elapsed/60:.1f} minutes")

    # Find best weights
    runs_dir = os.path.join(os.getcwd(), "runs", "detect", "train")
    if os.path.isdir(runs_dir):
        weights_dir = os.path.join(runs_dir, "weights")
        best_weights = os.path.join(weights_dir, "best.pt")
        if os.path.exists(best_weights):
            return best_weights

    return ""


def export_to_onnx(weights_path: str, assets_dir: str) -> str:
    """
    Export trained model to ONNX opset=11.
    D-11d: opset=11 required for cv2.dnn compatibility.
    Returns: path to exported ONNX file.
    """
    print(f"\n[EXPORT] Exporting to ONNX (opset=11)...")

    cmd = [
        sys.executable, "-m", "ultralytics", "detect", "export",
        f"model={weights_path}",
        "format=onnx",
        "imgsz=640",
        "opset=11",
        "verbose=True",
    ]

    result = subprocess.run(cmd, cwd=os.getcwd())

    if result.returncode != 0:
        print(f"[ERROR] Export failed. Trying direct ONNX export...")
        try:
            from ultralytics import YOLO
            model = YOLO(weights_path)
            model.export(format="onnx", imgsz=640, opset=11)
            exported = weights_path.replace(".pt", ".onnx")
            if os.path.exists(exported):
                print(f"[OK] Fallback export: {exported}")
                return exported
        except Exception as e:
            print(f"[ERROR] Fallback export also failed: {e}")
            return ""

    # Find exported file
    onnx_candidates = [
        weights_path.replace(".pt", ".onnx"),
        os.path.join(os.path.dirname(weights_path), "best.onnx"),
    ]
    for candidate in onnx_candidates:
        if os.path.exists(candidate):
            return candidate

    return ""


def install_model(onnx_path: str, assets_dir: str) -> bool:
    """Install the trained ONNX model to assets/models/yolo_gpo.onnx."""
    models_dir = os.path.join(assets_dir, "models")
    os.makedirs(models_dir, exist_ok=True)

    dest = os.path.join(models_dir, "yolo_gpo.onnx")
    shutil.copy2(onnx_path, dest)
    print(f"\n[INSTALL] Model installed: {dest}")
    print(f"[OK] {os.path.getsize(dest) / 1024 / 1024:.1f} MB")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="YOLO Training Pipeline for Zedsu Phase 11. "
                    "D-11b: CLI-only training. D-11b-03: auto-detect CUDA/CPU. "
                    "D-11c-01: auto-backup on success."
    )
    parser.add_argument(
        "--dataset", default="dataset_yolo",
        help="Dataset root folder (default: dataset_yolo)"
    )
    parser.add_argument(
        "--epochs", type=int, default=100,
        help="Number of training epochs (default: 100)"
    )
    parser.add_argument(
        "--model", default="yolo11n",
        choices=["yolo11n", "yolov8n", "yolov8s"],
        help="Model size (default: yolo11n)"
    )
    parser.add_argument(
        "--device", choices=["cuda", "cpu"], default=None,
        help="Training device (default: auto-detect)"
    )
    parser.add_argument(
        "--no-backup", action="store_true",
        help="Skip backing up the current model before training"
    )
    parser.add_argument(
        "--assets", default="assets",
        help="Assets directory (default: assets)"
    )

    args = parser.parse_args()

    # Step 0: Hardware detection
    device, hw_label, is_cuda = args.device, "CPU", False
    if args.device is None:
        device, hw_label, is_cuda = detect_hardware()

    print("=" * 50)
    print("YOLO Training Pipeline -- Zedsu Phase 11")
    print("=" * 50)
    print(f"Hardware: {hw_label} ({'fast' if is_cuda else 'slow: ~2-4h'})")
    print(f"Dataset: {args.dataset}")
    print(f"Epochs: {args.epochs}")
    print(f"Model: {args.model}.pt")
    print(f"Assets: {args.assets}")
    print("=" * 50)

    # Step 1: Ensure dataset structure
    if not ensure_dataset_structure(args.dataset):
        sys.exit(1)

    # Step 2: Create data.yaml
    data_yaml = create_data_yaml(args.dataset)
    if not data_yaml:
        print("[ERROR] Failed to create data.yaml")
        sys.exit(1)

    # Step 3: Backup current model
    backup_path = ""
    if not args.no_backup:
        backup_path = backup_current_model(args.assets)
        if backup_path:
            print(f"[BACKUP] Saved: {backup_path}")
        else:
            print("[INFO] No existing model to backup")

    # Step 4: Train
    weights_path = run_training(data_yaml, args.model, args.epochs, device)
    if not weights_path or not os.path.exists(weights_path):
        print("[ERROR] Training did not produce weights")
        sys.exit(1)

    # Step 5: Export to ONNX
    onnx_path = export_to_onnx(weights_path, args.assets)
    if not onnx_path or not os.path.exists(onnx_path):
        print("[ERROR] Export failed")
        sys.exit(1)

    # Step 6: Install
    if install_model(onnx_path, args.assets):
        print("\n" + "=" * 50)
        print("TRAINING COMPLETE")
        print("=" * 50)
        print(f"Model: assets/models/yolo_gpo.onnx")
        if backup_path:
            print(f"Backup: {backup_path}")
        print(f"Restart Zedsu to load the new model.")


if __name__ == "__main__":
    main()
